import { useEffect, useState } from 'react'
import type { AsrGpuRuntimeDiagnostics, KnowledgeExtractionDiagnostics, MediaTempPreview, RetrievalDiagnostics, RuntimeMonitor, VideoCapabilityStatus } from '../../../shared/contracts/index.ts'
import { api } from '../api/client.ts'
import type { AppSnapshot } from '../app/types.ts'
import { Badge, Panel, StatusDot } from '../components/common.tsx'

export function SettingsPage({ snapshot, developerMode, advancedMode = false, onDeveloperMode, onAdvancedMode }: { snapshot: AppSnapshot; developerMode: boolean; advancedMode?: boolean; onDeveloperMode(value: boolean): void; onAdvancedMode?: (value: boolean) => void }): JSX.Element {
  const [backupMessage, setBackupMessage] = useState('')
  const [backupBusy, setBackupBusy] = useState(false)
  const [runtime, setRuntime] = useState<VideoCapabilityStatus | null>(snapshot.distribution?.media ?? null)
  const [runtimeBusy, setRuntimeBusy] = useState(false)
  const [asrDiagnostics, setAsrDiagnostics] = useState<AsrGpuRuntimeDiagnostics | null>(null)
  const [retrievalDiagnostics, setRetrievalDiagnostics] = useState<RetrievalDiagnostics | null>(null)
  const [knowledgeDiagnostics, setKnowledgeDiagnostics] = useState<KnowledgeExtractionDiagnostics | null>(null)
  const [mediaTemp, setMediaTemp] = useState<MediaTempPreview | null>(null)
  const [runtimeMonitor, setRuntimeMonitor] = useState<RuntimeMonitor | null>(null)
  const [cleanupMessage, setCleanupMessage] = useState('')
  const [desktopInfo, setDesktopInfo] = useState<{ product: string; version: string; build_id: string; data_root: string; log_root: string; desktop: true } | null>(null)
  const [closeBehavior, setCloseBehavior] = useState<'tray' | 'exit'>('tray')
  useEffect(() => {
    let disposed = false
    const refresh = () => void Promise.all([api.asrDiagnostics(), api.retrievalDiagnostics(), api.knowledgeDiagnostics(), api.mediaTempPreview(), api.runtimeMonitor()]).then(([asr, retrieval, knowledge, temp, monitor]) => {
      if (disposed) return
      setAsrDiagnostics(asr); setRetrievalDiagnostics(retrieval); setKnowledgeDiagnostics(knowledge); setMediaTemp(temp); setRuntimeMonitor(monitor)
    }).catch(() => undefined)
    refresh()
    const timer = setInterval(refresh, 2000)
    return () => { disposed = true; clearInterval(timer) }
  }, [])
  useEffect(() => {
    if (!window.personalWorkbenchDesktop) return
    void Promise.all([window.personalWorkbenchDesktop.getInfo(), window.personalWorkbenchDesktop.getCloseBehavior()]).then(([info, behavior]) => { setDesktopInfo(info); setCloseBehavior(behavior) }).catch(() => undefined)
  }, [])
  const checks = (snapshot.health?.checks ?? []) as { id: string; label: string; status: string; summary: string; details?: unknown }[]
  const models = ((snapshot.models?.models ?? []) as Record<string, unknown>[])
  return <div className="page-stack">
    <Panel title="界面模式" subtitle="选择完成后会保存到本机配置，下次启动继续使用。"><div className="setting-list"><label><span><strong>普通模式</strong><small>面向日常使用，隐藏验收任务、内部标识和组件细节。</small></span><input aria-label="普通模式" type="radio" name="interface-mode" checked={!advancedMode} onChange={() => onAdvancedMode?.(false)} /></label><label><span><strong>高级模式</strong><small>显示诊断、运行日志、审核和工程验收记录。</small></span><input aria-label="高级模式" type="radio" name="interface-mode" checked={advancedMode} onChange={() => onAdvancedMode?.(true)} /></label></div></Panel>
    <header className="page-heading"><div><Badge tone="blue">设置</Badge><h1>本机运行与高级诊断</h1><p>普通任务无需编辑 Profile、Provider 或 YAML；诊断信息集中显示在此处。</p></div></header>
    <Panel title="系统状态" subtitle="可选组件缺少时，仍可使用已经准备完成的本机能力。"><div className="metric-grid"><div className="metric"><span>Workbench</span><strong>正常</strong><small>本机服务正在运行</small></div><div className="metric"><span>本地AI</span><strong>{snapshot.distribution?.first_run.ollama?.status === 'running' ? '正常' : '需要设置'}</strong><small>Ollama与通用模型</small></div><div className="metric"><span>本地检索</span><strong>{snapshot.distribution?.first_run.models?.some(model => model.role === 'embedding' && model.installed) ? '正常' : '需要设置'}</strong><small>文档语义搜索</small></div><div className="metric"><span>文档处理</span><strong>正常</strong><small>PDF与新版Office文档</small></div><div className="metric"><span>文字识别</span><strong>{runtime?.ocr.available ? '正常' : '不可用'}</strong><small>扫描页面与文字图片</small></div><div className="metric"><span>视频处理</span><strong>{runtime?.ffmpeg.available ? '正常' : '需要设置'}</strong><small>媒体与语音组件</small></div></div></Panel>
    {desktopInfo && <Panel title="桌面应用" subtitle="窗口、数据与诊断均由当前Windows用户管理。"><div className="setting-list"><label><span><strong>关闭窗口时</strong><small>选择“最小化到托盘”后，可从托盘菜单再次打开。</small></span><select value={closeBehavior} onChange={event => { const value = event.target.value as 'tray' | 'exit'; setCloseBehavior(value); void window.personalWorkbenchDesktop?.setCloseBehavior(value) }}><option value="tray">最小化到托盘</option><option value="exit">完全退出</option></select></label><label><span><strong>导出诊断信息</strong><small>只包含版本、组件状态和匿名化配置，不包含文档正文、提示词或个人记忆。</small></span><button onClick={() => void window.personalWorkbenchDesktop?.exportDiagnostics().then(result => { if (!result.canceled) setBackupMessage(`诊断信息已保存：${result.path ?? ''}`) })}>导出诊断</button></label></div><div className="metric-grid"><div className="metric"><span>版本</span><strong>{desktopInfo.version}</strong><small>Build {desktopInfo.build_id}</small></div><div className="metric"><span>数据目录</span><strong>{desktopInfo.data_root}</strong></div><div className="metric"><span>日志目录</span><strong>{desktopInfo.log_root}</strong></div></div></Panel>}
    <div className="settings-grid"><Panel title="普通设置"><div className="setting-list"><label><span><strong>默认工作区</strong><small>{snapshot.workspaces.allowedRoots[0] ?? '尚未配置'}</small></span><button>选择</button></label><label><span><strong>界面语言</strong><small>简体中文</small></span><select defaultValue="zh-CN"><option value="zh-CN">简体中文</option></select></label><label><span><strong>最近任务数量</strong><small>首页与历史列表</small></span><select defaultValue="20"><option>20</option><option>50</option></select></label><label><span><strong>开发模式</strong><small>允许界面读取测试 Research Memory</small></span><input type="checkbox" checked={developerMode} onChange={event => onDeveloperMode(event.target.checked)} /></label></div></Panel><Panel title="模型状态" subtitle={`模型请求只进入 ${snapshot.localConfig?.ollama_endpoint ?? '本机 Ollama'}`}><div className="model-list">{models.map(model => <article key={String(model.id)}><span className="model-icon">Q</span><div><strong>{String(model.id)}</strong><p>{String(model.role)}</p></div><Badge tone="green">已安装</Badge></article>)}</div></Panel></div>
    <Panel title="运行监控" subtitle="采样仅用于显示当前本机任务和资源概况；不会改变模型或媒体运行环境。"><div className="metric-grid"><div className="metric"><span>GPU</span><strong>{runtimeMonitor?.gpu.name ?? '未检测到 GPU'}</strong><small>{runtimeMonitor?.gpu.available ? `${runtimeMonitor.gpu.utilization_percent ?? '—'}% · ${runtimeMonitor.gpu.memory_used_mb ?? '—'} / ${runtimeMonitor.gpu.memory_total_mb ?? '—'} MiB` : 'nvidia-smi 当前不可用'}</small></div><div className="metric"><span>CPU</span><strong>{runtimeMonitor?.cpu.logical_cores ?? '—'} 核</strong><small>Workbench RSS {runtimeMonitor?.cpu.process_rss_mb ?? '—'} MiB</small></div><div className="metric"><span>内存</span><strong>{runtimeMonitor === null ? '—' : `${runtimeMonitor.memory.used_mb} / ${runtimeMonitor.memory.total_mb} MiB`}</strong><small>可用 {runtimeMonitor?.memory.free_mb ?? '—'} MiB</small></div><div className="metric"><span>当前模型</span><strong>{runtimeMonitor?.active_model ?? '当前没有模型任务'}</strong><small>{runtimeMonitor?.current_task?.current_stage ?? '空闲'}</small></div><div className="metric"><span>当前任务</span><strong>{runtimeMonitor?.current_task?.task_type ?? '无'}</strong><small>{runtimeMonitor?.current_task === null || runtimeMonitor?.current_task === undefined ? '没有运行中的任务' : `${runtimeMonitor.current_task.progress}% · ${runtimeMonitor.current_task.message}`}</small></div></div><div className="settings-actions"><button disabled={runtimeBusy} onClick={() => { setRuntimeBusy(true); void api.runtimeMonitor().then(setRuntimeMonitor).catch(error => setBackupMessage(String(error))).finally(() => setRuntimeBusy(false)) }}>{runtimeBusy ? '正在读取…' : '刷新运行监控'}</button></div></Panel>
    <Panel title="Portable Config" subtitle="启动时自动检测，可在迁移目录后统一调整"><div className="portable-config-grid">{snapshot.localConfig === null ? <p className="muted">尚未读取 local-config.json。</p> : Object.entries(snapshot.localConfig).map(([key, value]) => <article key={key}><span>{key}</span><code>{value}</code></article>)}</div></Panel>
    <Panel title="Media Runtime" subtitle="网址获取、媒体探测、关键帧 OCR 与离线转写全部在本机执行。"><div className="metric-grid"><div className="metric"><span>yt-dlp</span><strong>{runtime?.downloader.available ? 'available' : 'missing'}</strong><small>{runtime?.downloader.version ?? runtime?.downloader.reason ?? '待检查'}</small></div><div className="metric"><span>FFmpeg / ffprobe</span><strong>{runtime?.ffmpeg.available && runtime.ffprobe.available ? 'available' : 'missing'}</strong><small>{runtime?.ffmpeg.version ?? runtime?.ffmpeg.reason ?? '待检查'}</small></div><div className="metric"><span>Frame OCR</span><strong>{runtime?.ocr.available ? 'available' : 'missing'}</strong><small>{runtime?.ocr.engine ?? runtime?.ocr.reason ?? '待检查'}</small></div><div className="metric"><span>ASR Python</span><strong>{runtime?.asr.available ? 'available' : 'missing'}</strong><small>{runtime?.asr.device ?? 'auto'} / {runtime?.asr.compute_type ?? '—'}</small></div><div className="metric"><span>检索模式</span><strong>{runtime?.embedding.provider === 'local-hash-v1' ? '基础本地检索' : runtime?.embedding.provider ?? '—'}</strong><small>{runtime?.embedding.diagnostic ?? '待检查'}</small></div></div><div className="settings-actions"><button className="primary" disabled={runtimeBusy} onClick={() => { setRuntimeBusy(true); void api.recheckVideoRuntime().then(setRuntime).catch(error => setBackupMessage(String(error))).finally(() => setRuntimeBusy(false)) }}>{runtimeBusy ? '正在检测…' : '重新检测媒体组件'}</button></div></Panel>
    <Panel title="文档处理" subtitle="所有文档均为只读解析；系统不会执行宏、公式、嵌入对象或外部链接。"><div className="metric-grid"><div className="metric"><span>PDF</span><strong>文字读取</strong><small>扫描页按需使用本机文字识别</small></div><div className="metric"><span>DOCX</span><strong>章节 / 文字 / 表格</strong><small>不处理包含宏的文档</small></div><div className="metric"><span>PPTX</span><strong>课件文字 / 表格</strong><small>图片仅用于有限文字识别</small></div><div className="metric"><span>XLSX</span><strong>工作表 / 单元格 / 统计</strong><small>保留公式文本，不执行公式</small></div></div></Panel>
    <Panel title="ASR Runtime Diagnostics" subtitle="GPU 运行库仅注入离线转写子进程，父进程与 Windows PATH 保持原值。"><div className="metric-grid"><div className="metric"><span>GPU</span><strong>{asrDiagnostics?.gpu_name ?? '待检测'}</strong><small>{asrDiagnostics === null ? '—' : `${asrDiagnostics.gpu_memory_total_mb ?? '—'} MiB · Driver ${asrDiagnostics.driver_version ?? '—'}`}</small></div><div className="metric"><span>GPU ASR</span><strong>{asrDiagnostics?.status === 'available' ? 'Available' : 'Unavailable'}</strong><small>{asrDiagnostics?.fallback_reason ?? `${asrDiagnostics?.selected_device ?? '—'} / ${asrDiagnostics?.selected_compute_type ?? '—'}`}</small></div><div className="metric"><span>CUDA / cuBLAS / cuDNN</span><strong>{asrDiagnostics?.runtime_versions.cuda_runtime ?? '—'}</strong><small>{asrDiagnostics === null ? '—' : `cuBLAS ${asrDiagnostics.runtime_versions.cublas ?? '—'} · cuDNN ${asrDiagnostics.runtime_versions.cudnn ?? '—'}`}</small></div><div className="metric"><span>最近 Benchmark</span><strong>{asrDiagnostics?.benchmark === null || asrDiagnostics?.benchmark === undefined ? '待执行' : `${asrDiagnostics.benchmark.summary.mean_speedup.toFixed(2)}×`}</strong><small>{asrDiagnostics?.benchmark === null || asrDiagnostics?.benchmark === undefined ? '尚无 CPU/GPU 对照' : `CPU RTF ${asrDiagnostics.benchmark.summary.mean_cpu_rtf.toFixed(3)} · GPU RTF ${asrDiagnostics.benchmark.summary.mean_gpu_rtf.toFixed(3)}`}</small></div><div className="metric"><span>Peak VRAM</span><strong>{asrDiagnostics?.benchmark?.summary.peak_vram_mb ?? '—'} MiB</strong><small>nvidia-smi 采样峰值</small></div><div className="metric"><span>CPU 回退验证</span><strong>{asrDiagnostics?.fallback_validation?.fallback_used ? 'Passed' : '待执行'}</strong><small>{asrDiagnostics?.fallback_validation === null || asrDiagnostics?.fallback_validation === undefined ? '尚无受控回退记录' : `${asrDiagnostics.fallback_validation.resolved_device} / ${asrDiagnostics.fallback_validation.compute_type} · ${asrDiagnostics.fallback_validation.duration_ms} ms`}</small></div><div className="metric"><span>进程环境</span><strong>{asrDiagnostics?.process_path_unchanged ? '父进程未改变' : '需要检查'}</strong><small>DLL 目录仅用于 ASR 子进程</small></div></div><div className="settings-actions"><button className="primary" disabled={runtimeBusy} onClick={() => { setRuntimeBusy(true); void Promise.all([api.recheckVideoRuntime(), api.recheckAsrDiagnostics()]).then(([media, diagnostics]) => { setRuntime(media); setAsrDiagnostics(diagnostics) }).catch(error => setBackupMessage(String(error))).finally(() => setRuntimeBusy(false)) }}>{runtimeBusy ? '正在检测…' : '重新检测 ASR GPU'}</button></div></Panel>
    <Panel title="Retrieval Runtime" subtitle="专用 Embedding 与 local-hash-v1 使用版本化索引，可以在同一语料上执行对照。">
      <div className="metric-grid">
        <div className="metric"><span>Provider</span><strong>{retrievalDiagnostics?.provider ?? '待检测'}</strong><small>{retrievalDiagnostics?.runtime ?? '—'}</small></div>
        <div className="metric"><span>Model</span><strong>{retrievalDiagnostics?.model ?? '—'}</strong><small>{retrievalDiagnostics?.dimension ?? '—'} 维</small></div>
        <div className="metric"><span>Runtime Status</span><strong>{retrievalDiagnostics?.formal_provider_available ? 'Available' : 'Fallback'}</strong><small>{retrievalDiagnostics?.formal_provider_diagnostic ?? '正在读取'}</small></div>
        <div className="metric"><span>Index Count</span><strong>{retrievalDiagnostics?.indexed_entities.total ?? 0}</strong><small>Segment {retrievalDiagnostics?.indexed_entities.video_segments ?? 0} · Knowledge {retrievalDiagnostics?.indexed_entities.knowledge_points ?? 0}</small></div>
        <div className="metric"><span>Staged / Approved</span><strong>{retrievalDiagnostics?.indexed_entities.staged ?? 0} / {retrievalDiagnostics?.indexed_entities.approved ?? 0}</strong><small>Embedding不会自动发布知识</small></div>
        <div className="metric"><span>Fallback</span><strong>local-hash-v1</strong><small>基础本地检索模式</small></div>
      </div>
      {retrievalDiagnostics?.benchmark && <div className="benchmark-overview">
        <header><div><span>固定 Benchmark</span><strong>{retrievalDiagnostics.benchmark.query_count} Queries / {retrievalDiagnostics.benchmark.corpus_size} Entities</strong></div><Badge tone={retrievalDiagnostics.benchmark.selected_default === 'semantic' ? 'green' : 'amber'}>默认：{retrievalDiagnostics.benchmark.selected_default === 'semantic' ? '语义检索' : '基础检索'}</Badge></header>
        <div className="benchmark-comparison">
          <article><span>local-hash-v1</span><strong>R@3 {(retrievalDiagnostics.benchmark.baseline.recall_at_3 * 100).toFixed(1)}%</strong><small>MRR {(retrievalDiagnostics.benchmark.baseline.mrr_at_5 * 100).toFixed(1)}% · {retrievalDiagnostics.benchmark.baseline.average_query_latency_ms.toFixed(1)} ms</small></article>
          <article><span>{retrievalDiagnostics.benchmark.semantic_model}</span><strong>R@3 {(retrievalDiagnostics.benchmark.semantic.recall_at_3 * 100).toFixed(1)}%</strong><small>MRR {(retrievalDiagnostics.benchmark.semantic.mrr_at_5 * 100).toFixed(1)}% · {retrievalDiagnostics.benchmark.semantic.average_query_latency_ms.toFixed(1)} ms</small></article>
          <article><span>中文语义改写</span><strong>{(retrievalDiagnostics.benchmark.chinese_semantic.mrr_at_5 * 100).toFixed(1)}%</strong><small>基础检索 {(retrievalDiagnostics.benchmark.chinese_baseline.mrr_at_5 * 100).toFixed(1)}%</small></article>
        </div>
      </div>}
      <div className="settings-actions"><button className="primary" disabled={runtimeBusy} onClick={() => { setRuntimeBusy(true); void Promise.all([api.rebuildRetrievalIndex(), api.retrievalDiagnostics()]).then(([, diagnostics]) => setRetrievalDiagnostics(diagnostics)).catch(error => setBackupMessage(String(error))).finally(() => setRuntimeBusy(false)) }}>{runtimeBusy ? '正在处理…' : '更新本机向量索引'}</button></div>
    </Panel>
    <Panel title="Knowledge Extraction Runtime" subtitle="qwen3:8b 只读取已有 Video Segment，并将 Knowledge Card 保持在 staged 状态等待人工检查。">
      <div className="metric-grid">
        <div className="metric"><span>Provider</span><strong>{knowledgeDiagnostics?.status === 'available' ? 'Available' : 'Unavailable'}</strong><small>{knowledgeDiagnostics?.provider ?? 'qwen3_local'} · localhost</small></div>
        <div className="metric"><span>Model</span><strong>{knowledgeDiagnostics?.model ?? 'qwen3:8b'}</strong><small>thinking=false · temperature {knowledgeDiagnostics?.temperature ?? 0}</small></div>
        <div className="metric"><span>Prompt</span><strong>{knowledgeDiagnostics?.prompt_version ?? 'knowledge-extraction-v1'}</strong><small>JSON Schema · 每段最多 {knowledgeDiagnostics?.maximum_cards_per_segment ?? 5} 张</small></div>
        <div className="metric"><span>Knowledge Cards</span><strong>{knowledgeDiagnostics?.card_count ?? 0}</strong><small>staged {knowledgeDiagnostics?.staged ?? 0} · approved {knowledgeDiagnostics?.approved ?? 0}</small></div>
        <div className="metric"><span>来源复核</span><strong>{knowledgeDiagnostics?.needs_grounding_review ?? 0}</strong><small>可能重复 {knowledgeDiagnostics?.possible_duplicates ?? 0} · 同源重复 {knowledgeDiagnostics?.same_source_duplicates ?? 0}</small></div>
        <div className="metric"><span>长期 Memory</span><strong>Manual Review</strong><small>结构化提取不会自动发布</small></div>
      </div>
      {knowledgeDiagnostics?.latest_benchmark && <div className="benchmark-overview knowledge-benchmark-overview">
        <header><div><span>Legacy / Structured 固定 A/B</span><strong>{knowledgeDiagnostics.latest_benchmark.corpus_size} Segments</strong></div><Badge tone={knowledgeDiagnostics.latest_benchmark.selected_default === 'structured' ? 'green' : 'amber'}>默认：{knowledgeDiagnostics.latest_benchmark.selected_default === 'structured' ? 'Structured' : 'Legacy'}</Badge></header>
        <div className="benchmark-comparison">
          <article><span>Schema / Source</span><strong>{(knowledgeDiagnostics.latest_benchmark.schema_valid_rate * 100).toFixed(1)}% / {(knowledgeDiagnostics.latest_benchmark.source_link_rate * 100).toFixed(1)}%</strong><small>数字定位 {(knowledgeDiagnostics.latest_benchmark.numeric_grounding_pass_rate * 100).toFixed(1)}%</small></article>
          <article><span>Legacy Semantic</span><strong>R@3 {(knowledgeDiagnostics.latest_benchmark.legacy_retrieval.recall_at_3 * 100).toFixed(1)}%</strong><small>MRR {(knowledgeDiagnostics.latest_benchmark.legacy_retrieval.mrr_at_5 * 100).toFixed(1)}%</small></article>
          <article><span>Structured Semantic</span><strong>R@3 {(knowledgeDiagnostics.latest_benchmark.structured_retrieval.recall_at_3 * 100).toFixed(1)}%</strong><small>MRR {(knowledgeDiagnostics.latest_benchmark.structured_retrieval.mrr_at_5 * 100).toFixed(1)}%</small></article>
          <article><span>字符压缩比</span><strong>{knowledgeDiagnostics.latest_benchmark.compression_ratio.toFixed(2)}</strong><small>每段 {knowledgeDiagnostics.latest_benchmark.cards_per_segment.toFixed(2)} 张卡片</small></article>
        </div>
      </div>}
    </Panel>
    <Panel title="媒体临时目录维护" subtitle="范围固定为 runtime/media/temp；执行前列出文件和容量。">
      <div className="temp-cleanup-summary"><div><span>待清理文件</span><strong>{mediaTemp?.files.length ?? 0}</strong></div><div><span>合计容量</span><strong>{mediaTemp === null ? '—' : `${(mediaTemp.total_bytes / 1024).toFixed(1)} KiB`}</strong></div><code>{mediaTemp?.root ?? '读取中'}</code></div>
      {mediaTemp && mediaTemp.files.length > 0 && <details><summary>查看待清理列表</summary><ul>{mediaTemp.files.map(file => <li key={file.relative_path}><code>{file.relative_path}</code><span>{file.size_bytes.toLocaleString('zh-CN')} bytes</span></li>)}</ul></details>}
      <div className="settings-actions"><button disabled={mediaTemp === null || mediaTemp.files.length === 0} onClick={() => {
        if (!window.confirm(`仅清理 ${mediaTemp?.root ?? ''} 中列出的 ${mediaTemp?.files.length ?? 0} 个文件，是否继续？`)) return
        setRuntimeBusy(true); setCleanupMessage('')
        void api.cleanupMediaTemp().then(result => Promise.all([Promise.resolve(result), api.mediaTempPreview()])).then(([result, next]) => { setMediaTemp(next); setCleanupMessage(`已清理 ${result.removed.length} 个临时文件，共 ${result.total_bytes.toLocaleString('zh-CN')} bytes。`) }).catch(error => setCleanupMessage(String(error))).finally(() => setRuntimeBusy(false))
      }}>清理媒体临时文件</button>{cleanupMessage && <span>{cleanupMessage}</span>}</div>
    </Panel>
    <Panel title="发行与备份" subtitle="备份使用 SQLite 在线备份机制，Release Package 可以迁移到不同用户名与磁盘路径。"><div className="metric-grid"><div className="metric"><span>应用版本</span><strong>{snapshot.distribution?.app_version ?? '—'}</strong><small>Portable Config v{snapshot.localConfig?.config_version ?? '—'}</small></div><div className="metric"><span>备份数量</span><strong>{snapshot.distribution?.backup_count ?? 0}</strong><small>{snapshot.distribution?.latest_backup?.created_at ?? '尚未备份'}</small></div><div className="metric"><span>发布包</span><strong>{snapshot.distribution?.release_package.exists ? '已生成' : '待生成'}</strong><small>{snapshot.distribution?.release_package.sha256?.slice(0, 12) ?? '—'}</small></div><div className="metric"><span>首次运行</span><strong>{snapshot.distribution?.first_run.completed ? '完成' : '待确认'}</strong><small>目录与可选媒体适配器检查</small></div></div><div className="settings-actions"><button className="primary" disabled={backupBusy} onClick={() => { setBackupBusy(true); setBackupMessage(''); void api.createBackup().then(result => setBackupMessage(`备份已验证：${result.id}`)).catch(error => setBackupMessage(String(error))).finally(() => setBackupBusy(false)) }}>创建并验证备份</button>{backupMessage && <span>{backupMessage}</span>}</div></Panel>
    <Panel title="高级诊断" subtitle="路径和底层组件默认折叠"><div className="diagnostic-list">{checks.map(check => <details key={check.id}><summary><StatusDot status={check.status} /><span><strong>{check.label}</strong><small>{check.summary}</small></span><b>查看</b></summary><pre>{JSON.stringify(check.details ?? { summary: check.summary }, null, 2)}</pre></details>)}</div></Panel>
  </div>
}
